name: App CI
on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]
    branches:
      - 'main'

jobs:
  CI:
    if: (github.actor != 'dependabot[bot]') && (contains(github.head_ref, 'dependabot/') == false)
    name: Test Code
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup docker compose
        uses: KengoTODA/actions-setup-docker-compose@main
        with:
          version: '2.12.2'
      - name: setup just
        uses: extractions/setup-just@v1
      - name: init env file
        run: |
          touch .env
          echo -e "TOKEN=${{ secrets.TOKEN }}\n" >> .env
          echo -e "MONGO_URL=mongodb://cry:bot@mongo:27017\n" >> .env
      - name: test code
        run: 'just test'
